/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/dag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dag Status */
        get: operations["get_dag_status_api_knowledge_dag_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Report */
        get: operations["get_evaluation_report_api_eval_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Evaluation Plan */
        post: operations["apply_evaluation_plan_api_eval_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_api_course_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/base": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course Base */
        get: operations["get_course_base_api_course_base_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quiz/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Quiz */
        post: operations["submit_quiz_api_quiz_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Learning Events */
        post: operations["record_learning_events_api_learning_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/path/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Learning Path */
        get: operations["get_learning_path_api_path_get_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Memory Report */
        get: operations["get_memory_report_api_memory_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Info */
        get: operations["get_user_info_api_user_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/profile/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile History
         * @description 获取用户的历史对话消息。
         */
        get: operations["get_profile_history_api_chat_profile_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Profile */
        post: operations["chat_profile_api_chat_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Profile */
        post: operations["confirm_profile_api_profile_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/qa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Qa */
        post: operations["chat_qa_api_chat_qa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quiz/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Error Notebook */
        get: operations["get_error_notebook_api_quiz_errors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quiz/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Quiz */
        post: operations["generate_quiz_api_quiz_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resource/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Resources */
        post: operations["generate_resources_api_resource_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resource/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resources */
        get: operations["list_resources_api_resource_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resource/detail/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resource Detail */
        get: operations["resource_detail_api_resource_detail__resource_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resource/progress/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resource Progress */
        get: operations["resource_progress_api_resource_progress__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_task__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task/{task_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Task */
        post: operations["retry_task_api_task__task_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CodePayload */
        CodePayload: {
            /** Language */
            language: string;
            /** Code */
            code: string;
            /** Description */
            description: string;
        };
        /** CodeResourceDetail */
        CodeResourceDetail: {
            /** Id */
            id: string;
            /** Task Id */
            task_id?: string | null;
            /** Course Name */
            course_name?: string | null;
            /** Title */
            title: string;
            /** Media Url */
            media_url?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            resource_type: "code";
            payload: components["schemas"]["CodePayload"];
        };
        /** CourseBaseData */
        CourseBaseData: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Content Ready */
            content_ready: boolean;
            /** Is Demo */
            is_demo: boolean;
            /** Chapters */
            chapters: components["schemas"]["CourseChapterData"][];
        };
        /** CourseBaseResponse */
        CourseBaseResponse: {
            data: components["schemas"]["CourseBaseData"];
            /** Trace Id */
            trace_id: string;
        };
        /** CourseChapterData */
        CourseChapterData: {
            /** Path */
            path: string;
            /** Name */
            name: string;
            /** Documents */
            documents: components["schemas"]["CourseDocumentData"][];
        };
        /** CourseDocumentData */
        CourseDocumentData: {
            /** Id */
            id: string;
            /** Chapter Path */
            chapter_path: string;
            /** Filename */
            filename: string;
            /** File Type */
            file_type: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Preview Text */
            preview_text?: string | null;
            /** Media Url */
            media_url?: string | null;
        };
        /** CourseListResponse */
        CourseListResponse: {
            /** Data */
            data: components["schemas"]["CourseSummary"][];
            /** Trace Id */
            trace_id: string;
        };
        /** CourseSummary */
        CourseSummary: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Content Ready */
            content_ready: boolean;
            /** Is Demo */
            is_demo: boolean;
        };
        /** CurvePoint */
        CurvePoint: {
            /** Day */
            day: number;
            /** Retention */
            retention: number;
        };
        /** DashboardActivitySummary */
        DashboardActivitySummary: {
            /**
             * Total Events
             * @default 0
             */
            total_events: number;
            /**
             * This Week Events
             * @default 0
             */
            this_week_events: number;
            /**
             * Streak Days
             * @default 0
             */
            streak_days: number;
        };
        /** DashboardData */
        DashboardData: {
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name?: string | null;
            profile?: components["schemas"]["DashboardProfileSummary"];
            path?: components["schemas"]["DashboardPathProgress"];
            quiz?: components["schemas"]["DashboardQuizSummary"];
            /** Recent Resources */
            recent_resources?: components["schemas"]["DashboardRecentResource"][];
            activity?: components["schemas"]["DashboardActivitySummary"];
            /** Weak Points */
            weak_points?: components["schemas"]["DashboardWeakPoint"][];
        };
        /** DashboardPathProgress */
        DashboardPathProgress: {
            /**
             * Total Nodes
             * @default 0
             */
            total_nodes: number;
            /**
             * Completed Nodes
             * @default 0
             */
            completed_nodes: number;
            /**
             * Percent
             * @default 0
             */
            percent: number;
            /**
             * Course Name
             * @default
             */
            course_name: string;
        };
        /** DashboardProfileSummary */
        DashboardProfileSummary: {
            /**
             * Cognitive Style
             * @default
             */
            cognitive_style: string;
            /**
             * Learning Pace
             * @default
             */
            learning_pace: string;
            /**
             * Short Term Goal
             * @default
             */
            short_term_goal: string;
            /**
             * Profile Text
             * @default
             */
            profile_text: string;
        };
        /** DashboardQuizSummary */
        DashboardQuizSummary: {
            /**
             * Total Attempts
             * @default 0
             */
            total_attempts: number;
            /**
             * Avg Score
             * @default 0
             */
            avg_score: number;
        };
        /** DashboardRecentResource */
        DashboardRecentResource: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Resource Type */
            resource_type: string;
            /** Created At */
            created_at: string;
        };
        /** DashboardResponse */
        DashboardResponse: {
            data: components["schemas"]["DashboardData"];
            /** Trace Id */
            trace_id: string;
        };
        /** DashboardWeakPoint */
        DashboardWeakPoint: {
            /** Name */
            name: string;
            /** Frequency */
            frequency: number;
        };
        /** ErrorNotebookData */
        ErrorNotebookData: {
            /** Questions */
            questions: components["schemas"]["ErrorQuestionItem"][];
            /** Total Errors */
            total_errors: number;
            /** Unique Concepts */
            unique_concepts: number;
        };
        /** ErrorNotebookResponse */
        ErrorNotebookResponse: {
            data: components["schemas"]["ErrorNotebookData"];
            /** Trace Id */
            trace_id: string;
        };
        /** ErrorQuestionItem */
        ErrorQuestionItem: {
            /** Question Id */
            question_id: string;
            /** Attempt Id */
            attempt_id: string;
            /** Quiz Title */
            quiz_title: string;
            /** Prompt */
            prompt: string;
            /** Question Type */
            question_type: string;
            /** Options */
            options?: string[];
            /** User Answer */
            user_answer: string;
            /** Correct Answer */
            correct_answer: string;
            /** Explanation */
            explanation: string;
            /** Concept */
            concept: string;
            /** Created At */
            created_at: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["GatewayError"];
            /** Trace Id */
            trace_id: string;
        };
        /** EvaluationApplyRequest */
        EvaluationApplyRequest: {
            /** Report Id */
            report_id: string;
        };
        /** EvaluationApplyResponse */
        EvaluationApplyResponse: {
            data: components["schemas"]["LearningPathData"];
            /** Trace Id */
            trace_id: string;
        };
        /** EvaluationRecommendedChange */
        EvaluationRecommendedChange: {
            /** Stage Name */
            stage_name: string;
            /** Difficulty */
            difficulty: string;
            /** Reason */
            reason: string;
            /** Resource Id */
            resource_id?: string | null;
        };
        /** EvaluationReportData */
        EvaluationReportData: {
            /** Theory Score */
            theory_score: number;
            /** Practice Score */
            practice_score: number;
            /** Weak Points */
            weak_points: components["schemas"]["EvaluationWeakPoint"][];
            /** Recommended Changes */
            recommended_changes: components["schemas"]["EvaluationRecommendedChange"][];
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Course Name */
            course_name: string;
            /** Source Path Id */
            source_path_id: string;
            /** Applied Path Id */
            applied_path_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EvaluationReportResponse */
        EvaluationReportResponse: {
            data: components["schemas"]["EvaluationReportData"];
            /** Trace Id */
            trace_id: string;
        };
        /** EvaluationWeakPoint */
        EvaluationWeakPoint: {
            /** Name */
            name: string;
            /** Frequency */
            frequency: number;
        };
        /** GatewayError */
        GatewayError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /** Details */
            details?: unknown | null;
        };
        /** GatewayEvent */
        GatewayEvent: {
            /**
             * Event
             * @enum {string}
             */
            event: "task.started" | "agent.started" | "task.progress" | "content.delta" | "profile.patch" | "media.ready" | "resource.ready" | "task.completed" | "task.failed" | "heartbeat";
            /** Task Id */
            task_id: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /** Trace Id */
            trace_id: string;
            /** Current Agent */
            current_agent?: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Resource Type */
            resource_type?: ("handout" | "mindmap" | "quiz" | "code" | "video") | null;
            /**
             * Content
             * @default
             */
            content: string;
            /** Media Url */
            media_url?: string | null;
            /**
             * Finish Flag
             * @default false
             */
            finish_flag: boolean;
            /** Resource Ids */
            resource_ids?: string[];
            /** Profile Patch */
            profile_patch?: {
                [key: string]: unknown;
            } | null;
            error?: components["schemas"]["GatewayError"] | null;
            /**
             * Demo Mode
             * @default false
             */
            demo_mode: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandoutPayload */
        HandoutPayload: {
            /** Markdown */
            markdown: string;
        };
        /** HandoutResourceDetail */
        HandoutResourceDetail: {
            /** Id */
            id: string;
            /** Task Id */
            task_id?: string | null;
            /** Course Name */
            course_name?: string | null;
            /** Title */
            title: string;
            /** Media Url */
            media_url?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            resource_type: "handout";
            payload: components["schemas"]["HandoutPayload"];
        };
        /** KnowledgeDagNodeStatus */
        KnowledgeDagNodeStatus: {
            /** Kp Id */
            kp_id: string;
            /** Kp Name */
            kp_name: string;
            /** Difficulty */
            difficulty: number;
            /**
             * Category
             * @default
             */
            category: string;
            /** Prerequisites */
            prerequisites?: string[];
            /**
             * Status
             * @default untouched
             */
            status: string;
        };
        /** KnowledgeDagStatusResponse */
        KnowledgeDagStatusResponse: {
            /** Data */
            data: components["schemas"]["KnowledgeDagNodeStatus"][];
            /** Trace Id */
            trace_id: string;
        };
        /** LearningEventBatchData */
        LearningEventBatchData: {
            /** Accepted */
            accepted: number;
        };
        /** LearningEventBatchRequest */
        LearningEventBatchRequest: {
            /** User Id */
            user_id: string;
            /** Course Name */
            course_name: string;
            /** Events */
            events: components["schemas"]["LearningEventInput"][];
        };
        /** LearningEventBatchResponse */
        LearningEventBatchResponse: {
            data: components["schemas"]["LearningEventBatchData"];
            /** Trace Id */
            trace_id: string;
        };
        /** LearningEventInput */
        LearningEventInput: {
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "resource_opened" | "resource_closed" | "path_node_completed" | "question_asked" | "video_progress";
            /** Resource Id */
            resource_id?: string | null;
            /** Path Node Id */
            path_node_id?: string | null;
            /** Client Started At */
            client_started_at?: string | null;
            /** Client Ended At */
            client_ended_at?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** LearningPathData */
        LearningPathData: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Course Name */
            course_name: string;
            /** Version */
            version: number;
            /** Nodes */
            nodes: components["schemas"]["LearningPathNodeData"][];
        };
        /** LearningPathNodeData */
        LearningPathNodeData: {
            /** Id */
            id: string;
            /** Position */
            position: number;
            /** Stage Name */
            stage_name: string;
            /** Difficulty */
            difficulty: string;
            /** Resource Id */
            resource_id?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /** LearningPathResponse */
        LearningPathResponse: {
            data: components["schemas"]["LearningPathData"];
            /** Trace Id */
            trace_id: string;
        };
        /** MemoryAction */
        MemoryAction: {
            /** Knowledge Point Id */
            knowledge_point_id: string;
            /** Title */
            title: string;
            /** Minutes */
            minutes: number;
            /**
             * Action Type
             * @enum {string}
             */
            action_type: "recall" | "quiz" | "practice";
            /** Reason */
            reason: string;
        };
        /** MemoryBlockage */
        MemoryBlockage: {
            /** Knowledge Point Id */
            knowledge_point_id: string;
            /** Name */
            name: string;
            /** Reason */
            reason: string;
        };
        /** MemoryKnowledgePoint */
        MemoryKnowledgePoint: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Retention */
            retention: number;
            /** Base Mastery */
            base_mastery: number;
            /** Days Since Review */
            days_since_review: number;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "stable" | "review_soon" | "urgent";
            /** Curve */
            curve: components["schemas"]["CurvePoint"][];
            /** Recommendation */
            recommendation: string;
            blockage?: components["schemas"]["MemoryBlockage"] | null;
        };
        /** MemoryReportData */
        MemoryReportData: {
            /** Memory Health */
            memory_health: number;
            /** Summary */
            summary: string;
            /** Has Personal Evidence */
            has_personal_evidence: boolean;
            /** Knowledge Points */
            knowledge_points: components["schemas"]["MemoryKnowledgePoint"][];
            /** Today Actions */
            today_actions: components["schemas"]["MemoryAction"][];
        };
        /** MemoryReportResponse */
        MemoryReportResponse: {
            data: components["schemas"]["MemoryReportData"];
            /** Trace Id */
            trace_id: string;
        };
        /** MindMapNode */
        MindMapNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Parent Id */
            parent_id?: string | null;
        };
        /** MindMapPayload */
        MindMapPayload: {
            /** Nodes */
            nodes: components["schemas"]["MindMapNode"][];
        };
        /** MindMapResourceDetail */
        MindMapResourceDetail: {
            /** Id */
            id: string;
            /** Task Id */
            task_id?: string | null;
            /** Course Name */
            course_name?: string | null;
            /** Title */
            title: string;
            /** Media Url */
            media_url?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            resource_type: "mindmap";
            payload: components["schemas"]["MindMapPayload"];
        };
        /** ProfileChatRequest */
        ProfileChatRequest: {
            /** User Id */
            user_id: string;
            /** Chat Text */
            chat_text: string;
        };
        /** ProfileConfirmRequest */
        ProfileConfirmRequest: {
            /** User Id */
            user_id: string;
        };
        /** ProfileHistoryData */
        ProfileHistoryData: {
            /** Messages */
            messages: components["schemas"]["ProfileMessageData"][];
        };
        /** ProfileHistoryResponse */
        ProfileHistoryResponse: {
            data: components["schemas"]["ProfileHistoryData"];
            /** Trace Id */
            trace_id: string;
        };
        /** ProfileMessageData */
        ProfileMessageData: {
            /** Id */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /** QaRequest */
        QaRequest: {
            /** User Id */
            user_id: string;
            /** Question */
            question: string;
            /**
             * Answer Mode
             * @default text
             * @enum {string}
             */
            answer_mode: "text" | "image" | "video";
        };
        /** QuizGenerateRequest */
        QuizGenerateRequest: {
            /** User Id */
            user_id: string;
            /** Course Name */
            course_name: string;
            /**
             * Weak Point
             * @default
             */
            weak_point: string;
            /**
             * Count
             * @default 5
             */
            count: number;
        };
        /** QuizPayload */
        QuizPayload: {
            /** Questions */
            questions: components["schemas"]["QuizQuestion"][];
        };
        /** QuizQuestion */
        QuizQuestion: {
            /** Id */
            id: string;
            /**
             * Question Type
             * @enum {string}
             */
            question_type: "choice" | "blank" | "programming";
            /** Prompt */
            prompt: string;
            /** Options */
            options?: string[];
            /** Answer */
            answer: string;
            /** Explanation */
            explanation: string;
        };
        /** QuizQuestionResult */
        QuizQuestionResult: {
            /** Question Id */
            question_id: string;
            /** Correct */
            correct: boolean;
            /** Submitted Answer */
            submitted_answer: string;
            /** Expected Answer */
            expected_answer: string;
            /** Explanation */
            explanation: string;
        };
        /** QuizResourceDetail */
        QuizResourceDetail: {
            /** Id */
            id: string;
            /** Task Id */
            task_id?: string | null;
            /** Course Name */
            course_name?: string | null;
            /** Title */
            title: string;
            /** Media Url */
            media_url?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            resource_type: "quiz";
            payload: components["schemas"]["QuizPayload"];
        };
        /** QuizSubmitData */
        QuizSubmitData: {
            /** Attempt Id */
            attempt_id: string;
            /** Score */
            score: number;
            /** Results */
            results: components["schemas"]["QuizQuestionResult"][];
        };
        /** QuizSubmitRequest */
        QuizSubmitRequest: {
            /** User Id */
            user_id: string;
            /** Resource Id */
            resource_id: string;
            /** Answers */
            answers: {
                [key: string]: string;
            };
        };
        /** QuizSubmitResponse */
        QuizSubmitResponse: {
            data: components["schemas"]["QuizSubmitData"];
            /** Trace Id */
            trace_id: string;
        };
        /** QuizTaskAcceptedData */
        QuizTaskAcceptedData: {
            /** Task Id */
            task_id: string;
            /**
             * Status
             * @default queued
             */
            status: string;
        };
        /** QuizTaskResponse */
        QuizTaskResponse: {
            data: components["schemas"]["QuizTaskAcceptedData"];
            /** Trace Id */
            trace_id: string;
        };
        /** ResourceDetailResponse */
        ResourceDetailResponse: {
            /** Data */
            data: components["schemas"]["HandoutResourceDetail"] | components["schemas"]["MindMapResourceDetail"] | components["schemas"]["QuizResourceDetail"] | components["schemas"]["CodeResourceDetail"] | components["schemas"]["VideoResourceDetail"];
            /** Trace Id */
            trace_id: string;
        };
        /** ResourceGenerateRequest */
        ResourceGenerateRequest: {
            /** User Id */
            user_id: string;
            /** Course Name */
            course_name: string;
            /**
             * Weak Point
             * @default
             */
            weak_point: string;
            /** Resource Type List */
            resource_type_list: ("handout" | "mindmap" | "quiz" | "code" | "video")[];
        };
        /** ResourceListData */
        ResourceListData: {
            /** Resources */
            resources: components["schemas"]["ResourceSummary"][];
        };
        /** ResourceListResponse */
        ResourceListResponse: {
            data: components["schemas"]["ResourceListData"];
            /** Trace Id */
            trace_id: string;
        };
        /** ResourceSummary */
        ResourceSummary: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** Course Name */
            course_name: string;
            /**
             * Resource Type
             * @enum {string}
             */
            resource_type: "handout" | "mindmap" | "quiz" | "code" | "video";
            /** Title */
            title: string;
            /** Media Url */
            media_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StudentProfileData */
        StudentProfileData: {
            /**
             * Knowledge Foundation
             * @default 待采集
             */
            knowledge_foundation: string;
            /**
             * Cognitive Style
             * @default 待采集
             */
            cognitive_style: string;
            /** Weak Points */
            weak_points?: string[];
            /**
             * Learning Pace
             * @default 待采集
             */
            learning_pace: string;
            /** Content Preferences */
            content_preferences?: string[];
            /**
             * Short Term Goal
             * @default 待采集
             */
            short_term_goal: string;
        };
        /** TaskAcceptedData */
        TaskAcceptedData: {
            /** Task Id */
            task_id: string;
            /**
             * Status
             * @default queued
             */
            status: string;
            /**
             * Deduplicated
             * @default false
             */
            deduplicated: boolean;
            /** Retry Of Task Id */
            retry_of_task_id?: string | null;
        };
        /** TaskAcceptedResponse */
        TaskAcceptedResponse: {
            data: components["schemas"]["TaskAcceptedData"];
            /** Trace Id */
            trace_id: string;
        };
        /** UserInfoData */
        UserInfoData: {
            /** Exists */
            exists: boolean;
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name?: string | null;
            profile?: components["schemas"]["StudentProfileData"] | null;
            /**
             * Profile Confirmed
             * @default false
             */
            profile_confirmed: boolean;
        };
        /** UserInfoResponse */
        UserInfoResponse: {
            data: components["schemas"]["UserInfoData"];
            /** Trace Id */
            trace_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VideoPayload */
        VideoPayload: {
            /** Summary */
            summary: string;
            /** Poster Url */
            poster_url: string;
            /** Duration Seconds */
            duration_seconds: number;
        };
        /** VideoResourceDetail */
        VideoResourceDetail: {
            /** Id */
            id: string;
            /** Task Id */
            task_id?: string | null;
            /** Course Name */
            course_name?: string | null;
            /** Title */
            title: string;
            /** Media Url */
            media_url?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            resource_type: "video";
            payload: components["schemas"]["VideoPayload"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_dag_status_api_knowledge_dag_get: {
        parameters: {
            query: {
                user_id: string;
                course_name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDagStatusResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_dashboard_api_dashboard_get: {
        parameters: {
            query: {
                user_id: string;
                course_name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_evaluation_report_api_eval_report_get: {
        parameters: {
            query: {
                user_id: string;
                course_name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReportResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    apply_evaluation_plan_api_eval_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationApplyResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_courses_api_course_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseListResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_course_base_api_course_base_get: {
        parameters: {
            query: {
                course_name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseBaseResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    submit_quiz_api_quiz_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizSubmitResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    record_learning_events_api_learning_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningEventBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningEventBatchResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_learning_path_api_path_get_get: {
        parameters: {
            query: {
                user_id: string;
                course_name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningPathResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_memory_report_api_memory_report_get: {
        parameters: {
            query: {
                user_id: string;
                course_name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryReportResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_user_info_api_user_info_get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfoResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_profile_history_api_chat_profile_history_get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileHistoryResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chat_profile_api_chat_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileChatRequest"];
            };
        };
        responses: {
            /** @description GatewayEvent SSE 流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayEvent"];
                    "text/event-stream": unknown;
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirm_profile_api_profile_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfoResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chat_qa_api_chat_qa_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_error_notebook_api_quiz_errors_get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorNotebookResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generate_quiz_api_quiz_generate_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizTaskResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generate_resources_api_resource_generate_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAcceptedResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_resources_api_resource_list_get: {
        parameters: {
            query: {
                user_id: string;
                course_name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceListResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resource_detail_api_resource_detail__resource_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceDetailResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resource_progress_api_resource_progress__task_id__get: {
        parameters: {
            query?: {
                after_seq?: number;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_task_api_task__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    retry_task_api_task__task_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAcceptedResponse"];
                };
            };
            /** @description 统一错误响应 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 统一错误响应 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 统一错误响应 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
