# Generated by Django 5.2.9 on 2026-01-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
