"""resources and learning

Revision ID: 670ecac21ddb
Revises: 2e03419b2f00
Create Date: 2026-07-10 22:33:19.934182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670ecac21ddb'
down_revision: Union[str, Sequence[str], None] = '2e03419b2f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_paths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('course_name', sa.String(length=160), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_name', 'version', name='uq_learning_path_version')
    )
    op.create_index(op.f('ix_learning_paths_course_name'), 'learning_paths', ['course_name'], unique=False)
    op.create_index(op.f('ix_learning_paths_status'), 'learning_paths', ['status'], unique=False)
    op.create_index(op.f('ix_learning_paths_user_id'), 'learning_paths', ['user_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('course_name', sa.String(length=160), nullable=False),
    sa.Column('resource_type', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_course_name'), 'resources', ['course_name'], unique=False)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_task_id'), 'resources', ['task_id'], unique=False)
    op.create_index(op.f('ix_resources_user_id'), 'resources', ['user_id'], unique=False)
    op.create_table('learning_path_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('path_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=120), nullable=False),
    sa.Column('difficulty', sa.String(length=24), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_id', 'position', name='uq_learning_path_node_position')
    )
    op.create_index(op.f('ix_learning_path_nodes_path_id'), 'learning_path_nodes', ['path_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_resource_id'), 'quiz_attempts', ['resource_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('learning_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('course_name', sa.String(length=160), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('path_node_id', sa.String(length=36), nullable=True),
    sa.Column('client_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['path_node_id'], ['learning_path_nodes.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_events_course_name'), 'learning_events', ['course_name'], unique=False)
    op.create_index(op.f('ix_learning_events_event_type'), 'learning_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_learning_events_path_node_id'), 'learning_events', ['path_node_id'], unique=False)
    op.create_index(op.f('ix_learning_events_resource_id'), 'learning_events', ['resource_id'], unique=False)
    op.create_index(op.f('ix_learning_events_user_id'), 'learning_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_events_user_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_resource_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_path_node_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_event_type'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_course_name'), table_name='learning_events')
    op.drop_table('learning_events')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_resource_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_learning_path_nodes_path_id'), table_name='learning_path_nodes')
    op.drop_table('learning_path_nodes')
    op.drop_index(op.f('ix_resources_user_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_task_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_course_name'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_learning_paths_user_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_status'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_course_name'), table_name='learning_paths')
    op.drop_table('learning_paths')
    # ### end Alembic commands ###
