"""course index

Revision ID: a9c9b73373c3
Revises: ce97c3788f13
Create Date: 2026-07-11 12:08:48.001838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c9b73373c3'
down_revision: Union[str, Sequence[str], None] = 'ce97c3788f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('root_path', sa.String(length=1000), nullable=False),
    sa.Column('content_ready', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=True)
    op.create_table('course_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('course_slug', sa.String(length=64), nullable=False),
    sa.Column('chapter_path', sa.String(length=500), nullable=False),
    sa.Column('chapter_name', sa.String(length=160), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=260), nullable=False),
    sa.Column('file_type', sa.String(length=24), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('preview_text', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=1200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_slug'], ['courses.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_slug', 'relative_path', name='uq_course_document_relative_path')
    )
    op.create_index(op.f('ix_course_documents_course_slug'), 'course_documents', ['course_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_documents_course_slug'), table_name='course_documents')
    op.drop_table('course_documents')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
